### ISSUE TITLE
Options.files undefined and erring out

### ISSUE THREAD

**Issue by JamiesonRoberts** [iamchristopher/simple-secure-server#4]
Code that has errors can be seen https://github.com/JamiesonRoberts/Jamieson-Roberts-Website/tree/feature-ghost-setup

And the error that is being returned is that files is undefined within the Options call

```
if (options.files) {
           ^
```

TypeError: Cannot read property 'files' of undefined
    at module.exports (/Users/jamiesonroberts/Websites/jr_express/node_modules/simple-secure-server/lib/index.js:9:16)
    at Object.<anonymous> (/Users/jamiesonroberts/Websites/jr_express/index.js:34:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by jorbascrumps** [comment]
I think I see what's happening. There's currently a bug that the options object is required. Try passing an empty object as the second parameter:

```
require('simple-secure-server')( app, {} );
```

**Comment by JamiesonRoberts** [comment]
Update error message from adding in the empty options object

```
   options.ports.default || 80,
                 ^
```

TypeError: Cannot read property 'default' of undefined
    at module.exports (/Users/jamiesonroberts/Websites/jr_express/node_modules/simple-secure-server/lib/index.js:15:22)
    at Object.<anonymous> (/Users/jamiesonroberts/Websites/jr_express/index.js:34:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by jorbascrumps** [comment]
I just pushed up a patch (#5) that _should_ fix this issue and make `options` truly optional. Can you give it a shot?

**Comment by JamiesonRoberts** [comment]
Seems to be working now, I'm getting an EACCESS error, but thats because its attempting to run on port 80, instead of 3000 as specified by the environment variables. At least as far as I can tell

**Comment by jorbascrumps** [comment]
That would be why! So you don't have to send in `options` anymore?

**Comment by JamiesonRoberts** [comment]
Correct, its working without the empty options
